name: 早安测试

on:
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
      - name: Send Message
        run: |
          curl "https://sctapi.ftqq.com/${{ secrets.SENDKEY }}.send" \
            --data-urlencode "title=☀️早安" \
            --data-urlencode "desp=测试成功"