name: 随机奖励小鱼干

on:
  schedule:
    - cron: '0 23 * * *'  # UTC23=北京时间07
    - cron: '0 3 * * *'   # UTC3=北京时间11
    - cron: '0 10 * * *'  # UTC10=北京时间18
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Send Daily Reminder
        run: |
          messages=(
            "今天不用做到满分，能开始就很好。"
            "别小看每天20分钟，它会慢慢改变很多东西。"
            "保持好奇心，比保持动力更容易坚持。"
            "允许自己慢一点，但不要停下来。"
            "如果今天只能完成一件事，请选那个半年后还值得庆祝的。 "
            "困的时候休息也是任务的一部分。"
            "不要把80%的精力，花在研究怎么做事情，先把事情做了。"
            "如果一直追逐即时反馈，就永远拿不到长期奖励。 "
            "允许今天只有60分，因为连续的60分比偶尔100分更厉害。"
            "允许自己普通，但不要停止前进。 "
            "灵感不会消失，它只是需要一点睡眠和咖啡。 "
            "今天请先完成一件『三个月后的自己会感谢你』的事情。剩下的时间，再去追逐即时快乐。  "
            
          )
          index=$((RANDOM % ${#messages[@]}))
          TODAY=$(TZ='Asia/Shanghai' date +%F)
          HOUR=$(TZ='Asia/Shanghai' date +%H)           
        # 转成数字，去掉前导零
           h=$((10#$HOUR))

          if [ $h -ge 7 ] && [ $h -lt 11 ]; then
            TITLE="🌅 开机成功！"
            DESP=$'### 今日启动\n今天最重要的一件事：\n- [ ] __________\n\n随机掉落一句话：\n'${messages[$index]}$'\n\n📅 '${TODAY}

          elif [ $h -ge 11 ] && [ $h -lt 18 ]; then
            TITLE="☀️喵😸"
            DESP=$'### 上午小提醒\n祝今天充满阳光和活力\n\n随机掉落一句话：\n'${messages[$index]}$'\n\n📅 '${TODAY}

          else
            TITLE="🌙 今天过得怎么样"
            DESP=$'### 今日复盘\n- [ ] 学习\n- [ ] 运动\n- [ ] 推进一个小项目\n\n今天最满意的一件小事：\n- __________\n\n随机掉落一句话：\n'${messages[$index]}$'\n\n📅 '${TODAY}
          fi


          curl -s -X POST \
            "https://sctapi.ftqq.com/${SENDKEY}.send" \
            --data-urlencode "title=$TITLE" \
            --data-urlencode "desp=$DESP"
          echo "推送结果码:$?"
        env:
          SENDKEY: ${{ secrets.SENDKEY }}
