name: 早安

on:
  schedule:
    - cron: '37 4 * * *'   # 每天 12:31（KST）
  workflow_dispatch:

jobs:
  remind:
    runs-on: ubuntu-latest

    steps:
      - name: 发送微信提醒
        run: |
          response=$(curl -s -X POST \
            "https://sctapi.ftqq.com/${{ secrets.SENDKEY }}.send" \
            --data-urlencode "title=⏰中午好～" \
            --data-urlencode "desp=记得吃饭 + 放松一下🍱")

          echo "$response"